#!/bin/bash

set -e
NAME="cfn-python-lint"
IMAGE_NAME=yokogawa/${NAME}
docker ps --quiet --all --filter name=${NAME} | xargs -r docker rm >/dev/null

set -x
if [ "${1}" = "bash" ]; then
    docker run -v ${PWD}:/work -i -t --name=${NAME} --entrypoint=sh ${IMAGE_NAME}
else
    docker run -v ${PWD}:/work -w /work --name=${NAME} ${IMAGE_NAME} $@
fi


